version: "3"
services:
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres
    ports:
      - "5432"
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/postgresql/data
  web:
    image: nginx
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
volumes:
  db-volume:
