# https://blog.codeship.com/running-rails-development-environment-docker

version: "2"
services:
  api:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:9.6.3
    ports:
      - "5432"
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/postgresql/data
  web:
    image: nginx
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
volumes:
  db-volume:
