// flow-typed signature: 625853ab45b0acf9277463d341aee455
// flow-typed version: <<STUB>>/some-sass-mixins_v^2.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'some-sass-mixins'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'some-sass-mixins' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'some-sass-mixins/docs/compile' {
  declare module.exports: any;
}

declare module 'some-sass-mixins/docs/highlight.pack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'some-sass-mixins/docs/compile.js' {
  declare module.exports: $Exports<'some-sass-mixins/docs/compile'>;
}
declare module 'some-sass-mixins/docs/highlight.pack.js' {
  declare module.exports: $Exports<'some-sass-mixins/docs/highlight.pack'>;
}
